# Generated by Django 3.2.9 on 2021-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='comments.Comment'),
        ),
    ]
